[project]
name = "langchain-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "michael-basweti", email = "baswetima@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.16.0",
    "duckduckgo-search>=8.1.1",
    "langchain>=1.3.16",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.0",
    "langchain-google-genai>=4.3.5",
    "python-dotenv>=1.2.3",
    "wikipedia>=1.4.0",
]

[project.scripts]
langchain-tutorial = "langchain_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
